### ISSUE TITLE
结果询问

### ISSUE THREAD

**Issue by Gao-Chengzhi** [JunyaoHu/2024-SJTU-AI-GoodsLine2Real#1]
哈喽，我是版权检测赛题的，想问一下你们出结果了吗？

**Comment by JunyaoHu** [comment]
没有啊，我一直在催主办方也没有回复，之前说的是“最晚12月中旬会出结果”

**Comment by Gao-Chengzhi** [comment]
我们也是，客服微信也不回 T.T

**Comment by JunyaoHu** [comment]
您好，

非常感谢您的耐心等待——比赛评审结果已经确认完毕（可以在这里查看：https://www.cs.sjtu.edu.cn/NewNoticeDetail.aspx?id=641 ）。

较为正式的竞赛评审结果的通知邮件的发放可能有些延迟，我们会在下周一之前完成所有的邮件发送工作。

感谢您对本次竞赛的热情，祝愿您的生活、学习、工作一切顺利。
@Gao-Chengzhi

**Comment by Gao-Chengzhi** [comment]
我也收到邮件了^.^

**Comment by JunyaoHu** [comment]
恭喜！🎉我没有名次了应该哈哈
